# Get python 3.12 slim image
FROM python:3.12-slim-bookworm

# The installer requires curl (and certificates) to download the release archive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates
RUN apt install curl git htop lsof vim tree nginx multitail -y

# Set working directory
WORKDIR /app

# Download the uv
# ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN curl -L -o /uv-installer.sh https://astral.sh/uv/install.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
ENV PATH="/root/.local/bin/:$PATH"

# Copy the application
COPY src/backend/ ./

# Install from requirements.txt
RUN uv pip install --system -r requirements.txt

# Run
CMD ["sh", "-c", "tree && python interactive-server.py"]

# Debug 
## ss -tuln (to check if the port is open)
## curl localhost:55000/serverHealth
## curl localhost:55000/